# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coyote < Formula
  desc "Coyote is a RabbitMQ message sink."
  homepage "https://github.com/ghokun/coyote"
  version "0.19.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghokun/coyote/releases/download/v0.19.0/coyote_0.19.0_darwin_amd64v3.tar.gz"
      sha256 "24899e6da71cef023eaba29721fe4b4420b659610e1b9e2c515cdfa7419ff68b"

      define_method(:install) do
        bin.install "coyote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghokun/coyote/releases/download/v0.19.0/coyote_0.19.0_darwin_arm64.tar.gz"
      sha256 "9d3b9b6dbe97cbee9d847b30c2468e8d0054e6407ea61f60960acc99b835cd48"

      define_method(:install) do
        bin.install "coyote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghokun/coyote/releases/download/v0.19.0/coyote_0.19.0_linux_amd64v3.tar.gz"
      sha256 "6d00a70f6f49b940d096fe2c21679f37468aa3039f12a6eed59cde7120b91f38"
      define_method(:install) do
        bin.install "coyote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghokun/coyote/releases/download/v0.19.0/coyote_0.19.0_linux_arm64.tar.gz"
      sha256 "70dd49f9ea4a065625f2b92f452120a68068bdff08639fea5964d9a088505c15"
      define_method(:install) do
        bin.install "coyote"
      end
    end
  end
end
