# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M3uChecker < Formula
  desc "Checks availability of streams in an m3u playlist and generates report"
  homepage "https://github.com/ghokun/m3u-checker"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/ghokun/m3u-checker/releases/download/v0.1.0/m3u-checker_0.1.0_darwin_amd64v3.tar.gz"
      sha256 "560f3e00a210636c73ae40b68f64ce7e521c54663c83140bba571aa160c77114"

      def install
        bin.install "m3u-checker"
      end
    end
    on_arm do
      url "https://github.com/ghokun/m3u-checker/releases/download/v0.1.0/m3u-checker_0.1.0_darwin_arm64.tar.gz"
      sha256 "cf86dc4f3f906ee244d7f91c597d88a89f8f94f48d2e92d115b78f2ac71808a3"

      def install
        bin.install "m3u-checker"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ghokun/m3u-checker/releases/download/v0.1.0/m3u-checker_0.1.0_linux_amd64v3.tar.gz"
        sha256 "ad631ace4f928cb5b7c65b248b59596f35067d08e21bc2542d6c130f2aa299f0"

        def install
          bin.install "m3u-checker"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ghokun/m3u-checker/releases/download/v0.1.0/m3u-checker_0.1.0_linux_arm64.tar.gz"
        sha256 "64ef556252ab8493eea03add39a5130f8110d28ae2e763e589b47637f825c881"

        def install
          bin.install "m3u-checker"
        end
      end
    end
  end
end
